function plotClickTrains(lTrain,rTrain,ct, rateLow, rateHigh)
% to visualize click trains:
h=1;
rate_low=rateLow;
rate_high=rateHigh;
ymin = -0.3;
ymax = 1.3;
plot(rTrain,ones(length(rTrain),1),...
    'LineStyle','none',...
    'Marker', 'o',...
    'MarkerFaceColor','blue',...
    'MarkerEdgeColor','blue',...
    'MarkerSize',6);
hold on
plot(lTrain,zeros(length(lTrain),1),...
    'LineStyle','none',...
    'Marker', 'o',...
    'MarkerFaceColor','red',...
    'MarkerEdgeColor','red',...
    'MarkerSize',6);

% draw vertical lines for change point locations
line([ct,ct]',repmat([ymin;ymax],1,length(ct)),...
    'Color',[.6,.6,.6],...
    'LineWidth',2)

hold off
title(['clicks; hazard= ',num2str(h),' Hz; low/high=',num2str(rate_low),...
    '/',num2str(rate_high),' Hz'])
xlabel('time in seconds')
ax=gca;
ax.LineWidth=2;
ax.YLim = [ymin,ymax];
ax.FontSize=16;
legend('right ear','left ear','change points', 'Location', 'westoutside')